# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginApps' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LoginApps

  target 'LoginApps-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginAppsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LoginApps-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LoginApps-tvOS

  target 'LoginApps-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
